import { config } from "dotenv";
config(); // load .env before connecting

import bcrypt from "bcryptjs";
import { connectDB, disconnectDB } from "./connect.js";
import { Hospital } from "./models/Hospital.js";
import { Doctor } from "./models/Doctor.js";
import { Service } from "./models/Service.js";
import { User } from "./models/User.js";
import { Admin } from "./models/Admin.js";

const hospitalSeed = [
  { name:"Apollo Hospitals", address:"123 Medical Avenue, Sector 5", city:"Pune", distance:2.5, rating:4.8, reviews:2341, beds:450, icuBeds:85, ots:18, level:"Premium", phone:"+91-20-6630-5000", email:"info@apollopune.com", website:"https://www.apollohospitals.com", facilities:["ICU","Emergency","Trauma Center","Pharmacy","Lab","Imaging","Cafeteria","Parking"], specialties:["Cardiology","Obstetrics","Orthopedics","Neurology","Oncology"], insurance:["HDFC ERGO","Aditya Birla","Bajaj Allianz","ICICI Lombard","Star Health"], aiScore:92, bestFor:["Cardiac Care","Maternity","Emergency Services"], doctors:[{name:"Dr. Rajesh Kumar",specialty:"Cardiology",experience:18,rating:4.9,availability:"Mon-Fri, 10am-5pm",consultationFee:1500},{name:"Dr. Priya Sharma",specialty:"Obstetrics",experience:14,rating:4.8,availability:"Mon-Sat, 9am-6pm",consultationFee:1200},{name:"Dr. Amit Patel",specialty:"Orthopedics",experience:16,rating:4.7,availability:"Tue-Sat, 11am-4pm",consultationFee:1300}], services:[{name:"CABG Surgery",category:"Cardiology",basePrice:450000,estimatedStay:7,description:"Coronary Artery Bypass Grafting"},{name:"Normal Delivery",category:"Obstetrics",basePrice:80000,estimatedStay:2},{name:"MRI Scan",category:"Diagnostics",basePrice:8000,estimatedStay:0},{name:"CT Scan",category:"Diagnostics",basePrice:6000,estimatedStay:0}] },
  { name:"Lilavati Hospital", address:"456 Health Plaza, Downtown", city:"Pune", distance:4.2, rating:4.7, reviews:1856, beds:380, icuBeds:72, ots:15, level:"Premium", phone:"+91-20-6630-6000", email:"info@lilavati.com", website:"https://www.lilavati.com", facilities:["ICU","Emergency","Pediatric Ward","Pharmacy","Lab","Imaging"], specialties:["Neurology","Pediatrics","Cardiology","Gastroenterology"], insurance:["HDFC ERGO","Aditya Birla","Bajaj Allianz","National Insurance"], aiScore:88, bestFor:["Neurological Care","Pediatric Services"], doctors:[{name:"Dr. Vikram Singh",specialty:"Neurology",experience:20,rating:4.9,availability:"Mon-Thu, 2pm-6pm",consultationFee:1800},{name:"Dr. Sneha Desai",specialty:"Pediatrics",experience:12,rating:4.8,availability:"Mon-Fri, 10am-4pm",consultationFee:1000}], services:[{name:"Angioplasty",category:"Cardiology",basePrice:350000,estimatedStay:5},{name:"Brain Surgery",category:"Neurology",basePrice:600000,estimatedStay:10},{name:"Vaccination Package",category:"Pediatrics",basePrice:5000,estimatedStay:0}] },
  { name:"Ruby Hall Clinic", address:"789 Medical Complex, Koregaon Park", city:"Pune", distance:5.8, rating:4.6, reviews:1432, beds:320, icuBeds:60, ots:12, level:"Standard", phone:"+91-20-6630-7000", email:"info@rubyhall.com", website:"https://www.rubyhall.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging","Cafeteria"], specialties:["Orthopedics","Dermatology","General Surgery"], insurance:["HDFC ERGO","Bajaj Allianz","ICICI Lombard"], aiScore:82, bestFor:["Orthopedic Surgery","Dermatology"], doctors:[{name:"Dr. Arun Verma",specialty:"Orthopedics",experience:15,rating:4.7,availability:"Tue-Sat, 10am-5pm",consultationFee:1200},{name:"Dr. Meera Nair",specialty:"Dermatology",experience:11,rating:4.6,availability:"Mon-Fri, 3pm-7pm",consultationFee:900}], services:[{name:"Joint Replacement",category:"Orthopedics",basePrice:280000,estimatedStay:6},{name:"Skin Treatment",category:"Dermatology",basePrice:15000,estimatedStay:0}] },
  { name:"Deenanath Mangeshkar Hospital", address:"321 Healthcare Street, Erandwane", city:"Pune", distance:3.1, rating:4.5, reviews:1205, beds:280, icuBeds:50, ots:10, level:"Standard", phone:"+91-20-6630-8000", email:"info@dmh.com", website:"https://www.dmh.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging"], specialties:["General Surgery","Internal Medicine"], insurance:["HDFC ERGO","Bajaj Allianz"], aiScore:78, bestFor:["General Surgery","Emergency Care"], doctors:[{name:"Dr. Sanjay Kulkarni",specialty:"General Surgery",experience:19,rating:4.8,availability:"Mon-Fri, 9am-5pm",consultationFee:1100}], services:[{name:"Appendectomy",category:"General Surgery",basePrice:120000,estimatedStay:3},{name:"Hernia Repair",category:"General Surgery",basePrice:100000,estimatedStay:2}] },
  { name:"Inamdar Hospital", address:"654 Medical Drive, Bibwewadi", city:"Pune", distance:6.5, rating:4.4, reviews:892, beds:220, icuBeds:40, ots:8, level:"Basic", phone:"+91-20-6630-9000", email:"info@inamdar.com", website:"https://www.inamdar.com", facilities:["Emergency","Pharmacy","Lab","Imaging"], specialties:["Internal Medicine","General Practice"], insurance:["HDFC ERGO"], aiScore:72, bestFor:["General Consultation","Diagnostics"], doctors:[{name:"Dr. Ramesh Joshi",specialty:"Internal Medicine",experience:17,rating:4.5,availability:"Mon-Sat, 10am-4pm",consultationFee:800}], services:[{name:"General Consultation",category:"Internal Medicine",basePrice:500,estimatedStay:0},{name:"Blood Test",category:"Diagnostics",basePrice:1500,estimatedStay:0}] },
  { name:"Jehangir Hospital", address:"987 Health Boulevard, Camp", city:"Pune", distance:2.8, rating:4.7, reviews:1678, beds:350, icuBeds:65, ots:14, level:"Premium", phone:"+91-20-6630-10000", email:"info@jehangir.com", website:"https://www.jehangir.com", facilities:["ICU","Emergency","Oncology Ward","Pharmacy","Lab","Imaging","Cafeteria"], specialties:["Oncology","Gastroenterology","Cardiology"], insurance:["HDFC ERGO","Aditya Birla","Bajaj Allianz","ICICI Lombard"], aiScore:85, bestFor:["Cancer Treatment","Gastroenterology"], doctors:[{name:"Dr. Isha Gupta",specialty:"Oncology",experience:16,rating:4.9,availability:"Mon-Fri, 11am-6pm",consultationFee:2000},{name:"Dr. Nikhil Deshmukh",specialty:"Gastroenterology",experience:13,rating:4.7,availability:"Tue-Sat, 2pm-7pm",consultationFee:1400}], services:[{name:"Chemotherapy",category:"Oncology",basePrice:200000,estimatedStay:5},{name:"Endoscopy",category:"Gastroenterology",basePrice:25000,estimatedStay:1}] },
  { name:"Fortis Hospital Pune", address:"Mulshi Road, Hinjewadi", city:"Pune", distance:8.2, rating:4.7, reviews:2100, beds:400, icuBeds:80, ots:16, level:"Premium", phone:"+91-20-6670-1000", email:"info@fortispune.com", website:"https://www.fortishealthcare.com", facilities:["ICU","Emergency","Trauma Center","Pharmacy","Lab","Imaging","Cafeteria","Parking","Blood Bank"], specialties:["Cardiology","Neurology","Orthopedics","Oncology","Transplant"], insurance:["HDFC ERGO","Aditya Birla","Bajaj Allianz","ICICI Lombard","Star Health","United India"], aiScore:90, bestFor:["Cardiac Surgery","Neuro Care","Transplant"], doctors:[{name:"Dr. Suresh Mehta",specialty:"Cardiology",experience:22,rating:4.9,availability:"Mon-Fri, 9am-4pm",consultationFee:2000},{name:"Dr. Kavita Rao",specialty:"Neurology",experience:18,rating:4.8,availability:"Mon-Sat, 10am-5pm",consultationFee:1800}], services:[{name:"Bypass Surgery",category:"Cardiology",basePrice:500000,estimatedStay:8},{name:"Knee Replacement",category:"Orthopedics",basePrice:300000,estimatedStay:5},{name:"PET Scan",category:"Diagnostics",basePrice:15000,estimatedStay:0}] },
  { name:"Sahyadri Hospital", address:"30 Karve Road, Deccan", city:"Pune", distance:3.5, rating:4.5, reviews:1560, beds:300, icuBeds:55, ots:11, level:"Standard", phone:"+91-20-6721-0000", email:"info@sahyadri.com", website:"https://www.sahyadrihospitals.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging","Cafeteria"], specialties:["Cardiology","Orthopedics","Gynecology","Pediatrics"], insurance:["HDFC ERGO","Bajaj Allianz","Star Health"], aiScore:80, bestFor:["Maternity","Pediatrics","Orthopedics"], doctors:[{name:"Dr. Anita Kulkarni",specialty:"Gynecology",experience:14,rating:4.7,availability:"Mon-Sat, 9am-5pm",consultationFee:1100},{name:"Dr. Prakash Jain",specialty:"Pediatrics",experience:10,rating:4.6,availability:"Mon-Fri, 10am-4pm",consultationFee:900}], services:[{name:"Cesarean Section",category:"Obstetrics",basePrice:150000,estimatedStay:3},{name:"Laparoscopy",category:"General Surgery",basePrice:90000,estimatedStay:2}] },
  { name:"KEM Hospital", address:"489 Rasta Peth, Sardar Moodliar Road", city:"Pune", distance:1.8, rating:4.3, reviews:3200, beds:600, icuBeds:100, ots:20, level:"Standard", phone:"+91-20-2612-6300", email:"info@kemhospital.com", website:"https://www.kemhospital.com", facilities:["ICU","Emergency","Trauma Center","Pharmacy","Lab","Imaging","Blood Bank"], specialties:["General Medicine","Surgery","Pediatrics","Gynecology","Orthopedics"], insurance:["HDFC ERGO","National Insurance","New India Assurance"], aiScore:75, bestFor:["Emergency Care","General Medicine","Affordable Care"], doctors:[{name:"Dr. Mohan Patil",specialty:"General Medicine",experience:20,rating:4.5,availability:"Mon-Sat, 8am-2pm",consultationFee:500},{name:"Dr. Sunita Bhosale",specialty:"Gynecology",experience:15,rating:4.4,availability:"Mon-Fri, 2pm-6pm",consultationFee:700}], services:[{name:"General Surgery",category:"Surgery",basePrice:80000,estimatedStay:3},{name:"X-Ray",category:"Diagnostics",basePrice:500,estimatedStay:0},{name:"Ultrasound",category:"Diagnostics",basePrice:1200,estimatedStay:0}] },
  { name:"Poona Hospital", address:"27 Sadashiv Peth, Tilak Road", city:"Pune", distance:2.2, rating:4.4, reviews:980, beds:250, icuBeds:45, ots:9, level:"Standard", phone:"+91-20-2445-2222", email:"info@poonahospital.com", website:"https://www.poonahospital.org", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging"], specialties:["Cardiology","Nephrology","Urology","General Surgery"], insurance:["HDFC ERGO","Bajaj Allianz","ICICI Lombard"], aiScore:76, bestFor:["Kidney Care","Urology","Cardiac"], doctors:[{name:"Dr. Deepak Sathe",specialty:"Nephrology",experience:16,rating:4.6,availability:"Mon-Fri, 10am-5pm",consultationFee:1200},{name:"Dr. Rajan Deshpande",specialty:"Urology",experience:14,rating:4.5,availability:"Tue-Sat, 11am-4pm",consultationFee:1100}], services:[{name:"Dialysis",category:"Nephrology",basePrice:3000,estimatedStay:0},{name:"Kidney Stone Removal",category:"Urology",basePrice:120000,estimatedStay:2}] },
  { name:"Medipoint Hospital", address:"Plot 1, Nagar Road, Yerwada", city:"Pune", distance:5.1, rating:4.5, reviews:1120, beds:200, icuBeds:38, ots:8, level:"Standard", phone:"+91-20-6600-1000", email:"info@medipoint.com", website:"https://www.medipointhospital.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging","Cafeteria"], specialties:["Orthopedics","Spine Surgery","Sports Medicine"], insurance:["HDFC ERGO","Bajaj Allianz","Star Health"], aiScore:79, bestFor:["Spine Surgery","Sports Injuries","Orthopedics"], doctors:[{name:"Dr. Nitin Bhalerao",specialty:"Spine Surgery",experience:17,rating:4.8,availability:"Mon-Fri, 9am-4pm",consultationFee:1500},{name:"Dr. Priti Wagh",specialty:"Sports Medicine",experience:9,rating:4.5,availability:"Mon-Sat, 10am-5pm",consultationFee:1000}], services:[{name:"Spine Surgery",category:"Orthopedics",basePrice:350000,estimatedStay:7},{name:"ACL Repair",category:"Sports Medicine",basePrice:180000,estimatedStay:3}] },
  { name:"Inlaks & Budhrani Hospital", address:"7-9 Koregaon Park", city:"Pune", distance:4.8, rating:4.6, reviews:1340, beds:280, icuBeds:52, ots:10, level:"Premium", phone:"+91-20-6681-0000", email:"info@inlaksbudhrani.com", website:"https://www.inlaksbudhrani.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging","Cafeteria","Parking"], specialties:["Cardiology","Oncology","Neurology","Gastroenterology"], insurance:["HDFC ERGO","Aditya Birla","Bajaj Allianz","ICICI Lombard"], aiScore:84, bestFor:["Cancer Care","Cardiac","Neurology"], doctors:[{name:"Dr. Ashok Bhatt",specialty:"Oncology",experience:21,rating:4.9,availability:"Mon-Fri, 10am-5pm",consultationFee:2200},{name:"Dr. Leena Joshi",specialty:"Cardiology",experience:15,rating:4.7,availability:"Mon-Sat, 9am-3pm",consultationFee:1600}], services:[{name:"Radiation Therapy",category:"Oncology",basePrice:250000,estimatedStay:0},{name:"Cardiac Catheterization",category:"Cardiology",basePrice:180000,estimatedStay:2}] },
  { name:"Aditya Birla Memorial Hospital", address:"Thergaon, Chinchwad", city:"Pune", distance:12.0, rating:4.7, reviews:1890, beds:420, icuBeds:78, ots:17, level:"Premium", phone:"+91-20-3071-7171", email:"info@abmhospital.com", website:"https://www.adityabirlahospital.com", facilities:["ICU","Emergency","Trauma Center","Pharmacy","Lab","Imaging","Cafeteria","Parking","Blood Bank","NICU"], specialties:["Cardiology","Neurology","Oncology","Pediatrics","Transplant","Orthopedics"], insurance:["HDFC ERGO","Aditya Birla","Bajaj Allianz","ICICI Lombard","Star Health","United India"], aiScore:91, bestFor:["Multi-Specialty","Transplant","Pediatric ICU"], doctors:[{name:"Dr. Rajendra Patil",specialty:"Cardiology",experience:24,rating:4.9,availability:"Mon-Fri, 9am-3pm",consultationFee:2500},{name:"Dr. Smita Kulkarni",specialty:"Pediatrics",experience:16,rating:4.8,availability:"Mon-Sat, 10am-5pm",consultationFee:1200}], services:[{name:"Heart Transplant",category:"Cardiology",basePrice:1500000,estimatedStay:21},{name:"Bone Marrow Transplant",category:"Oncology",basePrice:1200000,estimatedStay:30},{name:"NICU Care",category:"Pediatrics",basePrice:8000,estimatedStay:1}] },
  { name:"Noble Hospital", address:"153 Magarpatta City Road, Hadapsar", city:"Pune", distance:7.3, rating:4.4, reviews:1050, beds:240, icuBeds:44, ots:9, level:"Standard", phone:"+91-20-6760-0000", email:"info@noblehospital.com", website:"https://www.noblehospital.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging"], specialties:["General Medicine","Orthopedics","Gynecology","ENT"], insurance:["HDFC ERGO","Bajaj Allianz","National Insurance"], aiScore:74, bestFor:["General Medicine","ENT","Gynecology"], doctors:[{name:"Dr. Vinod Sharma",specialty:"ENT",experience:13,rating:4.5,availability:"Mon-Fri, 10am-5pm",consultationFee:800},{name:"Dr. Rekha Pawar",specialty:"Gynecology",experience:11,rating:4.4,availability:"Mon-Sat, 9am-2pm",consultationFee:900}], services:[{name:"Tonsillectomy",category:"ENT",basePrice:60000,estimatedStay:1},{name:"Hysterectomy",category:"Gynecology",basePrice:130000,estimatedStay:4}] },
  { name:"Sanjeevan Hospital", address:"Plot 12, Kothrud", city:"Pune", distance:4.0, rating:4.3, reviews:760, beds:180, icuBeds:32, ots:7, level:"Basic", phone:"+91-20-2528-0000", email:"info@sanjeevan.com", website:"https://www.sanjeevanhospital.com", facilities:["Emergency","Pharmacy","Lab","Imaging"], specialties:["General Practice","Internal Medicine","Dermatology"], insurance:["HDFC ERGO","National Insurance"], aiScore:68, bestFor:["General Practice","Skin Care","Affordable"], doctors:[{name:"Dr. Ganesh Kulkarni",specialty:"Internal Medicine",experience:12,rating:4.3,availability:"Mon-Sat, 9am-6pm",consultationFee:600},{name:"Dr. Pooja Desai",specialty:"Dermatology",experience:8,rating:4.4,availability:"Mon-Fri, 11am-5pm",consultationFee:700}], services:[{name:"Skin Biopsy",category:"Dermatology",basePrice:8000,estimatedStay:0},{name:"General Checkup",category:"Internal Medicine",basePrice:800,estimatedStay:0}] },
  { name:"Surya Mother & Child Care", address:"S. No. 44, Wakad", city:"Pune", distance:9.5, rating:4.6, reviews:1420, beds:150, icuBeds:30, ots:6, level:"Standard", phone:"+91-20-6720-0000", email:"info@suryahospital.com", website:"https://www.suryahospital.com", facilities:["ICU","NICU","Emergency","Pharmacy","Lab","Imaging"], specialties:["Obstetrics","Gynecology","Pediatrics","Neonatology"], insurance:["HDFC ERGO","Aditya Birla","Star Health"], aiScore:83, bestFor:["Maternity","Newborn Care","High-Risk Pregnancy"], doctors:[{name:"Dr. Madhuri Phadke",specialty:"Obstetrics",experience:18,rating:4.8,availability:"Mon-Sat, 9am-5pm",consultationFee:1300},{name:"Dr. Sunil Nair",specialty:"Neonatology",experience:14,rating:4.7,availability:"Mon-Fri, 10am-4pm",consultationFee:1400}], services:[{name:"High-Risk Delivery",category:"Obstetrics",basePrice:200000,estimatedStay:5},{name:"NICU Admission",category:"Neonatology",basePrice:10000,estimatedStay:1}] },
  { name:"Oyster & Pearl Hospital", address:"Plot 4, Baner Road", city:"Pune", distance:6.8, rating:4.5, reviews:890, beds:200, icuBeds:36, ots:8, level:"Standard", phone:"+91-20-6600-2000", email:"info@oysterpearl.com", website:"https://www.oysterpearl.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging","Cafeteria"], specialties:["Orthopedics","Physiotherapy","Rheumatology","Sports Medicine"], insurance:["HDFC ERGO","Bajaj Allianz","ICICI Lombard"], aiScore:77, bestFor:["Joint Care","Physiotherapy","Sports Injuries"], doctors:[{name:"Dr. Hemant Joshi",specialty:"Rheumatology",experience:15,rating:4.6,availability:"Mon-Fri, 10am-5pm",consultationFee:1200},{name:"Dr. Swati Gokhale",specialty:"Physiotherapy",experience:10,rating:4.5,availability:"Mon-Sat, 9am-6pm",consultationFee:700}], services:[{name:"Physiotherapy Session",category:"Physiotherapy",basePrice:1500,estimatedStay:0},{name:"Arthroscopy",category:"Orthopedics",basePrice:160000,estimatedStay:2}] },
  { name:"Lokmanya Hospital", address:"Chinchwad Station Road, Pimpri", city:"Pune", distance:14.0, rating:4.4, reviews:1100, beds:260, icuBeds:48, ots:10, level:"Standard", phone:"+91-20-2742-0000", email:"info@lokmanya.com", website:"https://www.lokmanyahospital.com", facilities:["ICU","Emergency","Pharmacy","Lab","Imaging","Blood Bank"], specialties:["General Surgery","Cardiology","Nephrology","Urology"], insurance:["HDFC ERGO","Bajaj Allianz","National Insurance","New India Assurance"], aiScore:73, bestFor:["Affordable Care","General Surgery","Kidney Care"], doctors:[{name:"Dr. Anil Pawar",specialty:"General Surgery",experience:18,rating:4.5,availability:"Mon-Fri, 9am-4pm",consultationFee:900},{name:"Dr. Shubhangi More",specialty:"Nephrology",experience:12,rating:4.4,availability:"Mon-Sat, 10am-3pm",consultationFee:1000}], services:[{name:"Cholecystectomy",category:"General Surgery",basePrice:95000,estimatedStay:2},{name:"Kidney Transplant",category:"Nephrology",basePrice:800000,estimatedStay:14}] },
  { name:"Pune Institute of Medical Sciences", address:"Vimannagar, Nagar Road", city:"Pune", distance:6.0, rating:4.5, reviews:1300, beds:310, icuBeds:58, ots:12, level:"Premium", phone:"+91-20-6680-0000", email:"info@pims.com", website:"https://www.pims.edu.in", facilities:["ICU","Emergency","Trauma Center","Pharmacy","Lab","Imaging","Cafeteria","Parking","Blood Bank"], specialties:["Cardiology","Neurology","Oncology","Orthopedics","Gastroenterology"], insurance:["HDFC ERGO","Aditya Birla","Bajaj Allianz","ICICI Lombard","Star Health"], aiScore:86, bestFor:["Multi-Specialty","Research","Advanced Diagnostics"], doctors:[{name:"Dr. Vivek Sathe",specialty:"Gastroenterology",experience:19,rating:4.8,availability:"Mon-Fri, 10am-5pm",consultationFee:1700},{name:"Dr. Nandini Kulkarni",specialty:"Oncology",experience:17,rating:4.7,availability:"Mon-Sat, 9am-4pm",consultationFee:2000}], services:[{name:"Colonoscopy",category:"Gastroenterology",basePrice:18000,estimatedStay:0},{name:"Immunotherapy",category:"Oncology",basePrice:300000,estimatedStay:3}] },
  { name:"Bharati Hospital", address:"Dhankawadi, Katraj Road", city:"Pune", distance:8.5, rating:4.3, reviews:2800, beds:700, icuBeds:120, ots:22, level:"Standard", phone:"+91-20-2437-0000", email:"info@bharatihospital.com", website:"https://www.bharatividyapeeth.edu", facilities:["ICU","Emergency","Trauma Center","Pharmacy","Lab","Imaging","Blood Bank","NICU"], specialties:["General Medicine","Surgery","Pediatrics","Gynecology","Orthopedics","Psychiatry"], insurance:["HDFC ERGO","National Insurance","New India Assurance","United India"], aiScore:71, bestFor:["Affordable Care","Teaching Hospital","Psychiatry"], doctors:[{name:"Dr. Santosh Jadhav",specialty:"Psychiatry",experience:16,rating:4.4,availability:"Mon-Fri, 9am-3pm",consultationFee:800},{name:"Dr. Varsha Patil",specialty:"General Medicine",experience:14,rating:4.3,availability:"Mon-Sat, 8am-2pm",consultationFee:500}], services:[{name:"Psychiatric Consultation",category:"Psychiatry",basePrice:1000,estimatedStay:0},{name:"Cataract Surgery",category:"Ophthalmology",basePrice:35000,estimatedStay:0}] }
];

async function seed() {
  await connectDB();
  await Promise.all([Hospital.deleteMany({}), Doctor.deleteMany({}), Service.deleteMany({}), User.deleteMany({}), Admin.deleteMany({})]);
  console.log("Cleared existing collections");

  for (const { doctors, services, ...hospitalData } of hospitalSeed) {
    const hospital = await Hospital.create(hospitalData);
    await Doctor.insertMany(doctors.map((d: any) => ({ ...d, hospitalId: hospital._id })));
    await Service.insertMany(services.map((s: any) => ({ ...s, hospitalId: hospital._id })));
    console.log("  Seeded:", hospital.name);
  }

  const userHash = await bcrypt.hash("user123", 10);
  await User.insertMany([
    { name:"Rajesh Kumar", email:"rajesh@example.com", phone:"+91-9876543210", passwordHash:userHash, status:"Active", appointments:5, joinDate:new Date("2024-01-15") },
    { name:"Priya Sharma", email:"priya@example.com", phone:"+91-9876543211", passwordHash:userHash, status:"Active", appointments:3, joinDate:new Date("2024-02-20") },
    { name:"Amit Patel", email:"amit@example.com", phone:"+91-9876543212", passwordHash:userHash, status:"Active", appointments:8, joinDate:new Date("2024-03-10") },
    { name:"Neha Singh", email:"neha@example.com", phone:"+91-9876543213", passwordHash:userHash, status:"Inactive", appointments:2, joinDate:new Date("2024-01-25") },
    { name:"Vikram Desai", email:"vikram@example.com", phone:"+91-9876543214", passwordHash:userHash, status:"Active", appointments:6, joinDate:new Date("2024-02-28") },
  ]);
  console.log("Seeded 5 users (password: user123)");

  const adminHash = await bcrypt.hash("admin1234", 10);
  await Admin.create({ name:"Admin User", email:"admin@smartcare.com", passwordHash:adminHash, role:"super_admin" });
  console.log("Seeded admin (email: admin@smartcare.com / password: admin1234)");

  await disconnectDB();
  console.log("\nSeed complete. 20 hospitals loaded.");
}

seed().catch((err) => { console.error(err); process.exit(1); });
